version: '3.9'
services:

  mysql:
    container_name: mysql
    image: mysql/mysql-server
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file: .env.mysql
    volumes:
      - $PWD/mysql:/var/lib/mysql
    networks:
      - dev

networks:
  dev:


volumes:
  mysql:
    external: true
